apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: p90rfhxkc-python 
  janus-idp.io/tekton: p90rfhxkc-python
  backstage.io/kubernetes-id: p90rfhxkc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p90rfhxkc-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  